language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
  - npm run lint
  - npm run test
  - npm run check-coverage
  - npm run build
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
